// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/edmarfelipe/go-wire/internal/drivers/db"
	"github.com/edmarfelipe/go-wire/internal/drivers/http"
	"github.com/edmarfelipe/go-wire/internal/usecases"
)

// Injectors from wire.go:

func InitializeUsecase() (*usecases.UpdateLatestLaunchsUsecase, error) {
	launchRepository := db.NewLaunchRepository()
	httpLaunchRepository := http.NewLaunchRepository()
	updateLatestLaunchsUsecase := usecases.NewUpdateLatestLaunchsUsecase(launchRepository, httpLaunchRepository)
	return updateLatestLaunchsUsecase, nil
}
